### ISSUE TITLE
displayField should not be hard-coded to 'name'

### ISSUE THREAD

**Issue by ajturner** [koopjs/koop-socrata#1]
See [this service](http://koop.dc.esri.com/socrata/nola/psp3-bvzw/FeatureServer/0) that doesn't have a field called `name`. If there is no name, default to the first string?

```json
{
"currentVersion": 10.21,
"id": 0,
"name": "psp3-bvzw",
"type": "Feature Layer",
"displayField": "name",
"description": "",
"copyrightText": "",
"defaultVisibility": true,
"relationships": [
...
```

**Comment by chelm** [comment]
display field is set to ID now.

**Comment by ajturner** [comment]
Is it always set to ID? Or does it pick up a better string attribute?

**Comment by chelm** [comment]
Its always set to id ATM, but could grab the first string field. This would change at the koop/core level, not in the provider. Though I bet it'd be smart to be able to have a provider pass in a field to use too...

**Comment by ajturner** [comment]
Keep ID for now - this is really an app level setting anyways. It can be configured via popup template in the item metadata.
