### ISSUE TITLE
When I add a socrata site to my instance of koop and restart node, I have to re-add it

### ISSUE THREAD

**Issue by sirws** [koopjs/koop-socrata#15]
Repro (On Windows)
Startup Node/Koop (simple app)
curl --data "host=http://data.wa.gov&id=wa" localhost:1337/socrata
Success!
Can access a socrata URL.
Stop node.
Restart node.
wa instance is gone.

**Comment by chelm** [comment]
Hey @sirws This is because the sample app is probably just using the Local cache not PostGIS. The Local cache sort of sucks in that it is only and in memory cache, so it get dropped on server stops.

**Comment by sirws** [comment]
in my config (koop-sample-app/config/default.json) file I have this:

{
    "server": {
        "port": 1337
    },
    "data_dir": "/usr/local/koop/",
    "db": {
      "conn": "postgres://<username>:<password>@localhost/koopdev"
    }
}

**Comment by chelm** [comment]
Ahh look at the server.js file though: https://github.com/koopjs/koop-sample-app/blob/master/server.js#L13-L15

You'll need those lines. Hope that helps!

**Comment by sirws** [comment]
<smacks head>
Duh!  Thanks for that.  It has been a couple weeks since I touched it last and that slipped through.

**Comment by chelm** [comment]
I think is good to close!
