### ISSUE TITLE
Socrata table not rendering properly in ArcGIS Online map viewer

### ISSUE THREAD

**Issue by sirws** [koopjs/koop-socrata#16]
http://www.arcgis.com/home/webmap/viewer.html?url=http://50.18.49.187/socrata/wa/3uf4-3kn2/FeatureServer/

Socrata data is a table.  Try to view the table in the ArcGIS Online map viewer and it doesn't render any records.  Must be some sort of formatting of the output from koop/socrata that is causing this issue.

![image](https://cloud.githubusercontent.com/assets/793576/7437680/825a9580-f00e-11e4-91b4-182352e50a19.png)

**Comment by chelm** [comment]
@sirws Im guessing that since its a Table it doesnt have any geometries show adding it to the map in AGO wont render anything, since it has nothing...

http://50.18.49.187/socrata/wa/3uf4-3kn2/FeatureServer/0/query -> see no geoms to map...

**Comment by sirws** [comment]
Yes, but the table is in the Table of Contents of the map (like I would expect)... and when I go to show the table, it gives me the above screenshot that doesn't show the grid of data, just the count of records...

**Comment by sirws** [comment]
Here is an example of a table coming from an ArcGIS Server feature service:

http://www.arcgis.com/home/webmap/viewer.html?url=http://sampleserver5.arcgisonline.com/arcgis/rest/services/SF311/FeatureServer/1

See how it renders data in the grid below?  Even if it is a table and not a layer:
![image](https://cloud.githubusercontent.com/assets/793576/7437869/a339152c-f010-11e4-900f-4f4c30026959.png)

**Comment by sirws** [comment]
Here is some more information.  It appears that the socrata provider is returning data that isn't expected in ArcGIS clients.

Attributes should only contain simple data types, and we are returning objects:
![image](https://cloud.githubusercontent.com/assets/793576/7458320/54963262-f248-11e4-9c72-d0ea94c227ad.png)

The "phone" field has an object in it.

Also, this is a table (non-spatial) and it is returning this info in the object:
hasZ: false,
hasM: false,
geometryType: "esriGeometryPoint",
spatialReference: {
wkid: 4326
},
All of that can be dropped from a table object.  ArcGIS Feature Services do not return that information for table objects.

**Comment by chelm** [comment]
@sirws Awesome, Yes I think the correct course of action would be to flatten these properties into something like: 

```
{ phone_phone_number: "123456789", ... }
```

We just need to be sure that those get turned into "fields" in the feature service out put as well. Probably a pretty simple to do in koop-socrata's model, in the `toGeoJSON` method...

**Comment by sirws** [comment]
Cool!  Also, I am seeing records that have fields / attributes that are not in the fields array:

![image](https://cloud.githubusercontent.com/assets/793576/7458701/5d7370cc-f24b-11e4-83b4-4839912fc8e1.png)

Note the object above has a "mobile_phone" attribute and fields collection does not contain a mobile_phone attribute:

![image](https://cloud.githubusercontent.com/assets/793576/7458717/86b47a94-f24b-11e4-8b57-e9525971bea0.png)

**Comment by chelm** [comment]
Right, that is an issue, if not THE issue :)

**Comment by chelm** [comment]
I've got an idea of what this is going to take: 

1. While processing features in `toGeoJson` build a list of all attributes a feature should have (all flattened objects become fields)
2. A second pass on the features is then required to ensure that each feature has each field.

I'm not stoked on the 2nd pass but since each incoming may only have a subset of the feilds AND since while we process features we will actually be creating new fields (as flattened objects) we need to take a final pass and add any missing fields.

**Comment by sirws** [comment]
@chelm Have you made any progress on this flattening effort?  Is there a different issues for it, or is this it?  Let me know if you want me to create a new issue...

**Comment by chelm** [comment]
@sirws Yes flattening is in master - https://github.com/koopjs/koop-socrata/commit/fd5a5559133099073171a8b45b4059b6faca1787#diff-8f1da6e78158e3e881a0eeceaef15258R197

**Comment by sirws** [comment]
This appears to be fixed.  Closing.
