### ISSUE TITLE
Cannot add item to ArcGIS online

### ISSUE THREAD

**Issue by dmfenton** [koopjs/koop-socrata#19]
Try to add this item: http://koop.dc.esri.com/socrata/seattle/5fn8-vtui/FeatureServer/0
Observe the service is not loading properly.
Response times seem to be really long across Koop-Socrata in general
![image](https://cloud.githubusercontent.com/assets/7832202/7686800/798041ac-fd66-11e4-8f3f-296e7258d553.png)

**Comment by dmfenton** [comment]
This dataset is cached and this endpoint takes 9 seconds to response. http://koop.dc.esri.com/socrata/nola/5fn8-vtui/FeatureServer/0
Something must be unhappy here...

**Comment by chelm** [comment]
@dmfenton sure, its 460k features that the provider is retrieving, building extents, and then returning. Super inefficient

**Comment by dmfenton** [comment]
But the data is already cached...I downloaded this as a csv already.

**Comment by chelm** [comment]
yes its cached but the socrata providers still talks to the database...

**Comment by dmfenton** [comment]
The response time may have nothing to do with it (though I'm not buying that it can't be faster). Here are the two calls make by ArcGIS Online:
- http://dc.mapsqa.arcgis.com/sharing/checkUrl.jsp?url=http%3A//koop.dc.esri.com/socrata/nola/5fn8-vtui/FeatureServer/0%3Ff%3Djson&f=json
- http://koop.dc.esri.com/socrata/nola/5fn8-vtui/FeatureServer/0?f=json&callback=dojo.io.script.jsonp_dojoIoScript1._jsonpCallback

**Comment by slibby** [comment]
@dmfenton Pretty sure the issue is that you can't register a feature service that only consists of tables. ArcGIS Server cannot publish a feature service without a spatial layer (as feature services are a capability of mapservers), so this is an edge case that would only work with Koop. It needs a dummy geography at least.

**Comment by slibby** [comment]
If the intent is to support a table-from-Koop the same way you support a csv, then there's some more work to do I think.

**Comment by dmfenton** [comment]
It can't publish a table service?

**Comment by slibby** [comment]
ArcGIS Server cannot publish a feature service without a spatial layer (as feature services are a capability of mapservers)

**Comment by dmfenton** [comment]
So a table service would have to be part of a map server?

**Comment by slibby** [comment]
Si Señor.

**Comment by dmfenton** [comment]
Can be worked-around with pure REST API calls.
