### ISSUE TITLE
Use $limit=0 when checking the cache

### ISSUE THREAD

**Issue by dmfenton** [koopjs/koop-socrata#20]
When checking if the cache is expired, there is no need to request all the data. 
E.g. 
https://data.nola.gov/resource/5fn8-vtui.json?$limit=0 vs
https://data.nola.gov/resource/5fn8-vtui.json

**Comment by dmfenton** [comment]
Maybe this is why this query is slow when doing it back to back?
http://koop.dc.esri.com/socrata/nola/w68y-xmk6/FeatureServer/0/query?where=1%3D1&returnGeometry=false&returnIdsOnly=true&orderByFields=&f=json&returnCountOnly=true

**Comment by chelm** [comment]
Unfortunately I dont think the checkCache code is currently working or actually being called. This needs to be addressed.

**Comment by dmfenton** [comment]
resolved by https://github.com/koopjs/koop-socrata/pull/32
