### ISSUE TITLE
optimize socrata paging 

### ISSUE THREAD

**Issue by chelm** [koopjs/koop-socrata#23]
We are seeing a massive slow down in socrata services that require paging of lots of data. One reason is that the current paging routing does not seem to be throttling its requests. It currently creates a list of pages to GET and immediately requests them. This is probably causing trouble on the server when we make 100 - 200 requests all at once for data.

The solution might be a scale it back a little bit and request pages a bit more slowly.

**Comment by dmfenton** [comment]
Sold on that:
![image](https://cloud.githubusercontent.com/assets/7832202/7706792/73366f06-fe1a-11e4-9770-693dca91a318.png)

**Comment by chelm** [comment]
I have completed this work and will create a PR for it soon. The new version will be 0.2.0 and will support more throttled page requests via a queue and will return 202 while datasets are paging...

**Comment by dmfenton** [comment]
Resolved by #24
