### ISSUE TITLE
Can't do Walk Time Analysis on simple point layer

### ISSUE THREAD

**Issue by nixta** [koopjs/koop-socrata#33]
Add the sample point layer to a map: http://koop.dc.esri.com/socrata/nola/fwm6-d78i/FeatureServer/0

Try to do a Walk time with default single 5 minute distance:

![2015-06-04_13-13-32](https://cloud.githubusercontent.com/assets/25374/7990089/85637012-0abc-11e5-9aa3-9fc5b44b17a6.png)

Get this error:

![2015-06-04_13-12-42](https://cloud.githubusercontent.com/assets/25374/7990097/909216a0-0abc-11e5-87d2-16270293ebad.png)

Here's a popup on one of those records:

![2015-06-04_13-11-54](https://cloud.githubusercontent.com/assets/25374/7990117/b979056a-0abc-11e5-920f-ba21639621d4.png)

**Comment by nixta** [comment]
BTW, that was the repo from the ReadMe on this repo.

Having trouble getting anything NYC Open Data Portal to work at all:
https://data.cityofnewyork.us/Environment/Botanical-Gardens/hrii-hezj --> http://koop.dc.esri.com/socrata/nyc/hrii-hezj gives me this error:
`Error converting data to GeoJSON: JSON not returned from Socrata or blank JSON returned`

**Comment by chelm** [comment]
@nixta hmm yeah looks odd https://data.cityofnewyork.us/resource/hrii-hezj.json

**Comment by chelm** [comment]
Looks like we still have some work to do on attributes that are objects. In this case it looks like a location param is getting added to the attributes and is an object, not flattened. 

http://koop.dc.esri.com/socrata/nola/fwm6-d78i/FeatureServer/0/query

**Comment by nixta** [comment]
Ah yeah, I see. Opening a separate issue for the NYC stuff. Issue #34

**Comment by chelm** [comment]
Ahh the version of koop-socrata on koop.dc is out of date. This is fixed in a v0.2.2 - will update the server.

**Comment by chelm** [comment]
Silly me. This just need to be re-cached. Working. Closing
