### ISSUE TITLE
NYC Socrata JSON invalid

### ISSUE THREAD

**Issue by nixta** [koopjs/koop-socrata#34]
If you visit https://data.cityofnewyork.us/Environment/Botanical-Gardens/hrii-hezj (and so http://koop.dc.esri.com/socrata/nyc/hrii-hezj) you get this error:

`Error converting data to GeoJSON: JSON not returned from Socrata or blank JSON returned`

The JSON request (https://data.cityofnewyork.us/resource/hrii-hezj.json) returns an error:

```JSON
{
  "error" : true,
  "message" : "Unrecognized arguments [jsonace]"
}
```

**Comment by dmfenton** [comment]
This is covered in #29
