### ISSUE TITLE
Koop-Socrata Cache Timer Not Expiring

### ISSUE THREAD

**Issue by pholleran** [koopjs/koop-socrata#45]
The Koop Cache timer is not expiring.

Environment:
- Ubuntu 14.04 EC2
- PostgreSQL 9.3.9 (w/PostGIS)
- Most recent build of loop-sample-app
- Most recent install of koop-socrata

STR:
-  Register Koop provider (data.detroitmi.gov)
- Access Koop service (http://koop-2082786455.us-east-1.elb.amazonaws.com/socrata/detroitmi/encd-2smf/)  (based on https://data.detroitmi.gov/Public-Safety/Today-s-Crime-Map/encd-2smf - "Today's reported crime"
- Access Koop service again on next day (there has to be a faster way to do this) and notice that the data is out of sync with the data.detroit.gov site,

@dmfenton

**Comment by ngoldman** [comment]
The latest release of `koop-socrata` (1.0.0) should resolve this. Thanks @dmfenton!
