### ISSUE TITLE
tests leave leftover logging/error messages

### ISSUE THREAD

**Issue by jgravois** [koopjs/koop-socrata#53]
a successful run of tests results in two leftover files in the root of the repository.

`..year-month-day` and `.error.year-month-day`.

> 2015-08-24T19:49:10.641Z error Could not get rowCount. count::https://data.seattle.gov/resource/missing.json?$select=count(*)::404

> 2015-08-24T19:49:10.642Z error Could not get metadata. meta::https://data.seattle.gov/views/missing.json::404

>2015-08-24T19:49:11.229Z error Could not get rowCount. Could not parse count JSON

>2015-08-24T19:49:11.737Z error Could not get rowCount. count::https://data.seattle.gov/resource/filtered.json?$select=count(*)::500

>2015-08-24T19:49:12.238Z error Could not get first row. first::https://data.seattle.gov/resource/countFail.json?$order=:id&$limit=1::500

a quick review seems to indicate we are logging behavior that the tests are provoking intentionally, so maybe it'd be best to just blow them away afterward?

**Comment by ngoldman** [comment]
I think Those paths are incorrect... `..filename` should be `../test.log.year-month-day` or something along those lines. @jgravois Can you `rm -rf node_modules` and make sure the local version of koop is up to date?

**Comment by jgravois** [comment]
i ran `npm cache clean && npm install` before logging this issue.  behavior is the same after physically blowing away `node_modules`, rerunning `npm install` and confirming that the local version of koop is `2.6.2`

**Comment by ngoldman** [comment]
:( ok, will look into it. log should really be `year-month-day.test.log`, not the other way around or `..filename`.

**Comment by ngoldman** [comment]
(that way it can get ignored by `*.log` in `.gitignore`)
