### ISSUE TITLE
Missing fields in Socrata datasets

### ISSUE THREAD

**Issue by sirws** [koopjs/koop-socrata#56]
https://data.wa.gov/Natural-Resources-Environment/Water-Right-Applications/9ubz-5r4b?

Once processed through koop, the GPM and DOMESTIC_UNITS fields are not available.
http://koop.dc.esri.com/socrata/wastate/9ubz-5r4b/FeatureServer

I think this is because we are only searching the first row:
https://data.wa.gov/resource/9ubz-5r4b.json?$order=:id&$limit=1

Any ideas?

**Comment by sirws** [comment]
You would think we could pull the fields from here instead:
https://data.wa.gov/api/views.json?method=getDefaultView&id=xc42-c7rk

**Comment by sirws** [comment]
Or, what about pulling the csv endpoint:
https://data.wa.gov/resource/9ubz-5r4b.csv?$order=:id&$limit=1

It appears to include all fields in there...

**Comment by jgravois** [comment]
closed via #58 (nice work @sirws!)
