### ISSUE TITLE
Unable to install on Windows

### ISSUE THREAD

**Issue by pandzel** [koopjs/koop-socrata#62]
Perhaps all files under test/fixtures have invalid names under Windows fs rules (colon ':' is not permitted).

**Comment by dmfenton** [comment]
@pandzel do things work if you do npm install --production?

**Comment by pandzel** [comment]
No. This is what i've got using nodejs v5.3.0:

C:\dev\rd\test>npm install koop-socrata --save --production
npm ERR! tar.unpack untar error C:\Users\pete5162\AppData\Roaming\npm-cache\koop-socrata\1.0.2\package.tgz
npm WARN EPACKAGEJSON test@1.0.0 No description
npm WARN EPACKAGEJSON test@1.0.0 No repository field.
npm ERR! Windows_NT 6.3.9600
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "ins
tall" "koop-socrata" "--save" "--production"
npm ERR! node v5.3.0
npm ERR! npm  v3.3.12
npm ERR! path C:\dev\rd\test\node_modules\.staging\koop-socrata-aec41c55b3e6f30d1c325171a6e62a54\test\fixtures\missing::
views.json
npm ERR! code ENOENT
npm ERR! errno -4058
npm ERR! syscall open

npm ERR! enoent ENOENT: no such file or directory, open 'C:\dev\rd\test\node_modules\.staging\koop-socrata-aec41c55b3e6f
30d1c325171a6e62a54\test\fixtures\missing::views.json'
npm ERR! enoent This is most likely not a problem with npm itself
npm ERR! enoent and is related to npm not being able to find a file.
npm ERR! enoent

npm ERR! Please include the following file with any support request:
npm ERR!     C:\dev\rd\test\npm-debug.log

**Comment by dmfenton** [comment]
Try again with Koop-Socrata 1.0.3. I sanitized all the filenames.

**Comment by pandzel** [comment]
It's working now. Thanks.
