### ISSUE TITLE
Error in the log file

### ISSUE THREAD

**Issue by pandzel** [koopjs/koop-socrata#63]
Occasionally, I am getting the following message on the log:

error: Error querying {"name":"error","length":210,"severity":"ERROR","code":"42883","hint":"No function matches the given name and argument types. You might need to add explicit type casts.","position":"72","file":"parse_func.c","line":"523","routine":"ParseFuncOrColumn","msg":"function st_geomfromgeojson(text) does not exist"}

This happens when making the following call (or similar):

http://localhost:1337/socrata/nola/hpm5-48nj

which gives me null in the response. What does it mean and how to deal with it.

**Comment by dmfenton** [comment]
Hi @pandzel sorry for being so slow to reply. You need to have Postgis enabled in your database. Try logging in to your DB with psql and typing `create extension postgis;`
