### ISSUE TITLE
needs updating

### ISSUE THREAD

**Issue by ngoldman** [koopjs/koop-socrata#7]
This module is still including a default config in YAML and the tests are requiring `mocha` and `koop-server`, neither of which are listed as dev dependencies or dependencies. Even when mocha, koop-server, and yaml modules are installed, I get a segmentation fault when trying to run the test. Needs to be brought up to speed with the latest version of `koop` and made usable.

**Comment by chelm** [comment]
ahh looks like my local dev env has some modules left over (yaml). I'll get it updated pronto.

**Comment by chelm** [comment]
@ngoldman I was thinking about updating this repo to include "standard" and to use tape for testing

**Comment by ngoldman** [comment]
:+1:

**Comment by ngoldman** [comment]
@chelm `bbox2extent` has a very simple implementation of standard + tape as a minimal testing suite:

* https://github.com/ngoldman/bbox2extent/blob/master/package.json#L24-L31
* https://github.com/ngoldman/bbox2extent/blob/master/test/index.js

The demands of this repo would be a bit more complex but if you want to give it a shot that might be useful as a starting point

**Comment by dmfenton** [comment]
This is in place
