### ISSUE TITLE
Socrata Cache not Expiring

### ISSUE THREAD

**Issue by pholleran** [koopjs/koop-socrata#9]
Source data: http://data.detroitmi.gov/resource/encd-2smf.json
* Last-Modified header: "Mon, 13 Apr 2015 21:11:05 PDT"
* Date header: "Tue, 14 Apr 2015 14:12:31 GMT"

Data already exists in Koop cache (postgre db)
* Table: Socrata:encd-2smf:0
* Entry in kooptimers table: id: Socrata:encd-2smf:timer; expires: '1428951734558'  (Mon, 13 Apr 2015, 19:02:14 GMT)

New request initiated for: http://detroitkoop-268609380.us-east-1.elb.amazonaws.com/socrata/detroitmi/encd-2smf/featureserver/0
* Koop does not drop expired cache, reports "old" data
* kooptimer remains set as expired 1428951734558 value

Only workaround have found is to drop the corresponding koop table, delete the corresponding row from kooptimers, and make a new request.

**Comment by chelm** [comment]
@pholleran I'll have a look, but this doesnt surprise me. Havent visited this in a while. Have you tried hitting the "/drop" endpoint? koop.com/socrata/:host/:id/drop

**Comment by chelm** [comment]
@pholleran that should drop the entire thing from the db, but really we need to understand why its not expiring. Like I said I'll try to take a peek today

**Comment by pholleran** [comment]
Thanks for the shortcut to the workaround. If we get this figured out I plan on figuring out the paging workflow for large datasets.

**Comment by chelm** [comment]
@pholleran cool. Re: paging. My current strategy for paging is to create an array of page reqs first. Then I pass each to a queue https://github.com/caolan/async#queue that makes each req. When each one completes I check to see if its the last one (also possible by adding a "drain" on the queue). There are several things to consider like how to handle requests to the same dataset while its currently paging.

**Comment by pholleran** [comment]
Thanks for the suggestions. The SODA API has support for paging in the requests, so I was thinking about trying it out first. http://dev.socrata.com/docs/paging.html

Looks pretty straight-forward as long as I modify the request to include an order clause.

**Comment by chelm** [comment]
@pholleran also Koop caches like pgcache have an insertPartial function, which means you can all `koop.Cache.insert` to insert create the tables for the features and then on each page call `koop.Cache.insertPartial` to insert each page. https://github.com/Esri/koop-pgcache/blob/master/index.js#L443

**Comment by chelm** [comment]
Will dig into the cache expiration today @pholleran

**Comment by chelm** [comment]
This looks like its a bigger issue in Koop and the central cache expiration code, still looking

**Comment by dmfenton** [comment]
Resolved in the newest minor version
